### ISSUE TITLE
Zombies not spawning

### ISSUE THREAD

**Issue by Steev93** [AlexMl/ZvP#44]
Everything work's go ingame and this:
http://prntscr.com/7eg2p6

noithin at all and it's all default setting's

**Comment by Steev93** [comment]
No matter what i do :L

http://prntscr.com/7egcrk
http://prntscr.com/7egcos
http://prntscr.com/7egcci
http://prntscr.com/7egci2
http://prntscr.com/7eg91u
http://prntscr.com/7eg2p6

**Comment by AlexMl** [comment]
Please send me the arena file the config file of zvp and the pluginlog.info per email at aublidev@gmail.com (or just use pastebin and post the links here)

**Comment by Steev93** [comment]
Done

**Comment by AlexMl** [comment]
Someone using worldguard too had similuar issues as you. He wrote
>I do want to add that I did have some trouble with Worldguard's flagging system when I set up the arenas. I added separate arena regions within a worldguarded region, set the priorities and the individual flags and mobs wouldn't spawn. I ended up asking the WG guy today and they told me that the deny-spawn flag on the parent and mob-spawning flag on the child cancelled themselves out so to speak. In order to get the mobs to spawn in the arena I had to use the WG flag command on the arena region as such: /region flag <arenaname> deny-spawn -e
Thought I'd share that. I saw a lot of forums where people were in a similar predicament and none of them got an answer.

([See here](http://dev.bukkit.org/bukkit-plugins/zombievsplayer/#c174))

You may have the same problem. If not check the console. If a StackOverflowError appears the arena is not setup correctly

**Comment by Steev93** [comment]
Hey,

So i am using Worldguard and i am getting those Error's but it seems to work,

Like i created a region around where i created the arena with Mob-spawning Allow then Denyspawn creeper,skeleton, ect ect but still no luck

**Comment by AlexMl** [comment]
The main problem is that the plugin generates a random location for zombies and checks if it is in the arena and if it is valid (means block is air and do not spawn in the air). If it is not valid it will get a new random location and check it again. That's the part that kinda causes an infinite circle.

I have to and will change that in the future but not now. 

To fix it you have to setup the arena correctly. The lowest and highest point must be inside the arena like floor and ceiling.

**Comment by Steev93** [comment]
Ahh i see

i'll film myself doing a setup next and see if i am doing it right, this prob be tomorrow some time

**Comment by Steev93** [comment]
So i redid the arena, and setup with Priority and mob-spawning allow, also /region flag deny-spawn -e

Nothin would spawn, i goto type /spawnmob zombie 4 and it starts to appear but then doesn't actually spawn them, as i have to spawn them manually; http://prntscr.com/7hgtds

**Comment by AlexMl** [comment]
I have another approach. Test my latest beta build but please make a backup
of your arena files. Just in case. After updating try the game again.

If nothing happens again I will prepare you a special development build.

https://github.com/AlexMl/ZvP/releases/ZvP-v2.7-B2

**Comment by Steev93** [comment]
So didn't work, but now cosole is filled with this:

16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:193) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.isValidLocation(ArenaArea.java:219) ~[?:?]
16.06 05:20:45 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.contains(ArenaArea.java:95) ~[?:?]
16.06 05:20:45 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:73) ~[?:?]
16.06 05:20:45 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:61) ~[?:?]
16.06 05:20:45 [Server] INFO at org.util.Polygon.ArenaPolygon.getRectangularMaximum(ArenaPolygon.java:90) ~[?:?]
16.06 05:20:45 [Server] INFO at java.awt.Polygon.getBounds(Polygon.java:317) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO at java.awt.Polygon.getBoundingBox(Polygon.java:335) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO at java.awt.Rectangle.getBounds(Rectangle.java:314) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO at java.awt.Rectangle.<init>(Rectangle.java:211) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO at java.awt.geom.Rectangle2D.<init>(Rectangle2D.java:511) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO at java.awt.geom.RectangularShape.<init>(RectangularShape.java:56) ~[?:1.8.0_45]
16.06 05:20:45 [Server] INFO java.lang.StackOverflowError
16.06 05:20:45 [Server] WARN Task #1143 for ZombieVsPlayer v2.7.0_DEV generated an exception
16.06 05:20:45 [Multicraft] Skipped 969 lines due to rate limit (30/s)
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:44 [Multicraft] Skipped 1023 lines due to rate limit (30/s)
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:193) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.isValidLocation(ArenaArea.java:219) ~[?:?]
16.06 05:20:43 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.contains(ArenaArea.java:95) ~[?:?]
16.06 05:20:43 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:73) ~[?:?]
16.06 05:20:43 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:61) ~[?:?]
16.06 05:20:43 [Server] INFO at org.util.Polygon.ArenaPolygon.getRectangularMaximum(ArenaPolygon.java:90) ~[?:?]
16.06 05:20:43 [Server] INFO at java.awt.Polygon.getBounds(Polygon.java:317) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO at java.awt.Polygon.getBoundingBox(Polygon.java:335) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO at java.awt.Rectangle.getBounds(Rectangle.java:314) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO at java.awt.Rectangle.<init>(Rectangle.java:211) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO at java.awt.geom.Rectangle2D.<init>(Rectangle2D.java:511) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO at java.awt.geom.RectangularShape.<init>(RectangularShape.java:56) ~[?:1.8.0_45]
16.06 05:20:43 [Server] INFO java.lang.StackOverflowError
16.06 05:20:43 [Server] WARN Task #1143 for ZombieVsPlayer v2.7.0_DEV generated an exception
16.06 05:20:43 [Multicraft] Skipped 996 lines due to rate limit (30/s)
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:198) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.getNewRandomLocation(ArenaArea.java:193) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.isValidLocation(ArenaArea.java:219) ~[?:?]
16.06 05:20:42 [Server] INFO at me.Aubli.ZvP.Game.ArenaArea.contains(ArenaArea.java:95) ~[?:?]
16.06 05:20:42 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:73) ~[?:?]
16.06 05:20:42 [Server] INFO at org.util.Polygon.ArenaPolygon.contains(ArenaPolygon.java:61) ~[?:?]
16.06 05:20:42 [Server] INFO at org.util.Polygon.ArenaPolygon.getRectangularMaximum(ArenaPolygon.java:90) ~[?:?]
16.06 05:20:42 [Server] INFO at java.awt.Polygon.getBounds(Polygon.java:317) ~[?:1.8.0_45]
16.06 05:20:42 [Server] INFO at java.awt.Polygon.getBoundingBox(Polygon.java:335) ~[?:1.8.0_45]
16.06 05:20:42 [Server] INFO at java.awt.Rectangle.getBounds(Rectangle.java:314) ~[?:1.8.0_45]
16.06 05:20:42 [Server] INFO at java.awt.Rectangle.<init>(Rectangle.java:211) ~[?:1.8.0_45]
16.06 05:20:42 [Server] INFO at java.awt.geom.Rectangle2D.<init>(Rectangle2D.java:511) ~[?:1.8.0_45]

**Comment by Steev93** [comment]
i'd just love to see this plugin working and a lot of players are looking forwards to it on hub.sky-mc.net > /server skyblock :)

**Comment by AlexMl** [comment]
Do you mind if I join your server for a moment?

**Comment by Steev93** [comment]
Sure
Perfectly fine

**Comment by Steev93** [comment]
Thanks heaps to Alex Resolving this issue

**Comment by Steev93** [comment]
Hey Alex you around?

**Comment by AlexMl** [comment]
Yeah always.

**Comment by Steev93** [comment]
May i grab a hand trying out poly arena

Using a Sphere shape

**Comment by AlexMl** [comment]
Go for it. Should be really self explaining

**Comment by Steev93** [comment]
How do i get the height out of it, like if i select all the ground ? then do it again?

**Comment by AlexMl** [comment]
One point of the "circle" has to be to lowest and another the highest
location. You can also use flat arenas then the height is irrelevant.

**Comment by Steev93** [comment]
118 Positions xD let's test this haha

**Comment by AlexMl** [comment]
I had a big map with 150 positions yesterday.
My plan is to have an automatic setup program.

**Comment by Steev93** [comment]
oh Please! haha user's kept asking for a big arena so thought to try it ad using a Sphere shape.

I might of done something wrong as it's saying the positions are not in the Arena

**Comment by AlexMl** [comment]
Seems like the y coordinate is not inside the shape

**Comment by Steev93** [comment]
gunna use W/E CUI so i can see the shape as i'm going

**Comment by AlexMl** [comment]
something like a overview is also planned

**Comment by Steev93** [comment]
http://prntscr.com/7hzkyp  :D

**Comment by Steev93** [comment]
http://prntscr.com/7hztwe

**Comment by Steev93** [comment]
Plugin all working fine, then just stop's... http://prntscr.com/7i16c5

xD

**Comment by AlexMl** [comment]
Pictures tell me nothing. Does it happen again?

**Comment by Steev93** [comment]
Oh i deleted it after i checked log's it went to Standby mode cause not enough player Joined :) i believe with check in morning to late
