### ISSUE TITLE
Add whitelist for commands to block warping etc.

### ISSUE THREAD

**Issue by Steev93** [AlexMl/ZvP#48]
Not sure if Bug,

Users are able to leave the game like Warping or Spawning out.

So far i am using Region Flags to block any commands but /zvp

Maybe a white-list could be added so only commands in that list could be used

**Comment by Steev93** [comment]
Oh and Potions wouldn't Splash so i allowed that through a Flag also.

**Comment by AlexMl** [comment]
Withelist for commands. Got it

**Comment by Steev93** [comment]
Awesome!
