### ISSUE TITLE
Death choice?

### ISSUE THREAD

**Issue by Steev93** [AlexMl/ZvP#51]
Death choice, last to survive wins

So once a user is dead they are dead and cannot join, or has to go back in join mid game is on kinda thing. If this make sence

**Comment by AlexMl** [comment]
It would be the hell to change that.

**Comment by Steev93** [comment]
Fair enough only a thought to a suggestion :p

Sent from my HTC on the Telstra Mobile network

----- Reply message -----

**Comment by AlexMl** [comment]
Fixed with upcoming update. Introduction of ArenaMode and support of Deathmatch similar to Last man Standing
