### ISSUE TITLE
Add Option to enable or disable pvp in arena

### ISSUE THREAD

**Issue by Steev93** [AlexMl/ZvP#52]
Choice to have PvP Enabled or Disabled 

If Diabled, try to not give off Spam Messages of PvP is not allowed

**Comment by AlexMl** [comment]
Some other plugins of yours causing the message. It is not from zvp.

**Comment by Steev93** [comment]
Okay thanks :)

Sent from my HTC on the Telstra Mobile network

----- Reply message -----
