### ISSUE TITLE
Lobbys

### ISSUE THREAD

**Issue by korleorion** [AlexMl/ZvP#72]
Hi there,

Excuse my English, but I am using a translator of Spanish.

I have done all the steps you indicate in your plugin. I followed the video step by step.

The thing is that when I create the preLobby, get a message saying it's right.
But it's not like that. Because I put posters and tells me that the lobby (1) does not exist.
Pongo (/zvp list lobby) and no result appears.

The commands you've used in order are:

/ zvp add sand (I select the two points and all good)
/ zvp add position (selected at four points and all good)
/ zvp add one preLobby (the message says everything went well)
/ zvp add 1 lobby (the message says everything went well)

I put a poster:

Line 1: [zvp]
Line 2: 1
Line 2: 1
Line 4: shop

And he says that there is no lobby.

What can I do?

**Comment by AlexMl** [comment]
You missed to add a lobby. Use

/zvp add lobby

and everything will be fixed.
